stages:
  - test
  - build
  - deploy

cache:
  paths:
    - .m2/repository

Test:
  stage: test
  script:
    - mvn test
  allow_failure: true

Build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/

Deploy:
  stage: deploy
  script:
    - scp /target/rest-api-1.0-SNAPSHOT.war  -i ~/marketplace_homolog.pem -t ec2-user@172.54.1.38:/opt/wildfly/standalone/deployments/rest-api-1.0-SNAPSHOT.war